networks: 
  develop-network:
    driver: bridge

services:
  database:
    container_name: postgresql
    image: postgres:17.5
    ports:
      - 5432:5432
    restart: always
    env_file: ".env"
    volumes:
      - $PWD/database/data:/var/lib/postgresql/data
      - $PWD/scripts/init_db.sql:/docker-entrypoint-initdb.d/init_product.sql
    networks:
      - develop-network

  n8n :
    container_name: n8n 
    image: docker.n8n.io/n8nio/n8n
    ports:
      - 5678:5678
    restart: always
    user: root
    environment:
      - GENERIC_TIMEZONE=America/Sao_Paulo
      - TZ=America/Sao_Paulo
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_HOST=database
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=root
      - DB_POSTGRESDB_SCHEMA=public
      - DB_POSTGRESDB_PASSWORD=secret
    volumes:
      - $PWD/n8n_data:/home/node/
    networks:
      - develop-network